apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlka
  labels:
    app : htmlka

spec:
  replicas: 3
  selector:
     matchLabels:
       app: htmlka
  template:
    metadata:
      labels:
       app: htmlka
    spec:
      containers:
        - name : htmlka
          image: anttohha/htmlka:latest
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: htmlka-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: htmlka
