---
- name: Install httpd and run html and php 80 8081
  become: yes
  hosts: localhost

  tasks:
   - name: Install to host
     apt:
       name:
         - lxc
         - lxc-templates
         - python3-lxc
       state: latest

   - name: add template to ansible
     action: shell ansible-galaxy collection install community.general

   - name: Create htmlka
     community.general.lxc_container:
       name: html
       template: download
       state: started
       template_options: --dist centos --release 8-Stream --arch amd64
       container_command: |
         yum install httpd -y

   - name: Create phpka
     community.general.lxc_container:
       name: php
       template: download
       state: started
       template_options: --dist centos --release 8-Stream --arch amd64
       container_command: |
         yum install php httpd -y

   
  
   - name: Download playlist2
     action: shell sudo wget https://raw.githubusercontent.com/anttohha/devops-hometasks/master/task-03/02/playlist2.yaml
     
   - name: Download bash to bash
     action: shell sudo wget https://raw.githubusercontent.com/anttohha/devops-hometasks/master/task-03/02/2.sh
        
   - name: execute playbook
     action: shell ansible-playbook playlit2.yaml
     
   - name: add route to container
     action: shell sudo  bash 2.sh
