FROM debian:latest
RUN apt-get -y update && apt-get install -y sshpass git  ansible   locales   docker.io
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

WORKDIR /root/
COPY . /root/
RUN ansible-galaxy install -r /root/requirements.yaml
EXPOSE 80
RUN ansible-playbook /root/install.yaml
RUN usermod -aG docker jenkins
WORKDIR /var/lib/jenkins
CMD /usr/bin/daemon --foreground --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080 --prefix=
