---
- name: For stag and prod
  hosts: staging.vm, production.vm
  become: yes

  tasks:

   - name: to slave
     shell:  sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

   - name: to slave 2
     service:
      name: sshd
      state: restarted


   - name: install sshpass
     become: yes
     apt:
      name: sshpass
      state: present

   - name: disable key check
     become: yes
     ini_file:
      path: /etc/ansible/ansible.cfg
      section: defaults
      option: host_key_checking
      value: False




   - name: Install jq packages
     become: yes
     apt:
      name: jq
      state: present

   - name: Creates directory /opt/wordcloud for service
     file:
      path: /opt/wordcloud
      state: directory


   - name: chmod 777 /opt/wordcloud
     shell: sudo chmod 777 /opt/wordcloud

   - name: Copy service file
     copy:
      src: wordcloud.service
      dest:  /etc/systemd/system/wordcloud.service

   - name: Start wordcloud
     ansible.builtin.service:
      name: wordcloud
      state: restarted
