# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder "." , "/vagrant", disabled: false

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "2"
   end

   config.vm.define "staging.vm" do |staging|
       staging.vm.hostname = "staging.vm"
       staging.vm.network "private_network", ip: "192.168.56.12"
       staging.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1"
       staging.vm.provision "ansible_local" do |ansible|

          ansible.playbook = "for_stag_prod.yaml"
          ansible.become = true

        end
     end

     config.vm.define "production.vm" do |production|
         production.vm.hostname = "production.vm"
         production.vm.network "private_network", ip: "192.168.56.13"
         
         production.vm.provision "ansible_local" do |ansible|

            ansible.playbook = "for_stag_prod.yaml"
            ansible.become = true

          end
       end




   config.vm.define "nexus.vm" do |nexus|
       nexus.vm.hostname = "nexus.vm"
       nexus.vm.network "private_network", ip: "192.168.56.11"
       nexus.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
       nexus.vm.provision "ansible_local" do |ansible|
        #  ansible.galaxy_role_file = 'roles_for_nexus.yaml'
          ansible.playbook = "main_nexus.yaml"
          ansible.become = true

        end
     end



config.vm.define "jenkins.vm" do |jenkins|
   jenkins.vm.hostname = "jenkins.vm"
   jenkins.vm.network "private_network", ip: "192.168.56.10"
   jenkins.vm.provision "ansible_local" do |ansible|
    ansible.galaxy_role_file = 'requirements.yaml'
    ansible.playbook = "install.yaml"
    ansible.become = true

 end
end
end
