   - name: required pckgs install
     apt:
      pkg:
       - curl
       - apt-transport-https
       - gnupg
       - git
       - build-essential
       - python3-pip
      state: latest

   - name: install python-jenkins with pip
     pip:
       name:
       - python-jenkins
       - lxml

   - name: install java
     ansible.builtin.apt:
       name: openjdk-11-jre


   - name: ensure the jenkins apt repository key is installed
     apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present


   - name: ensure the repository is configured
     apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        update_cache: true




   - name: Install Jenkins
     apt:
      pkg:
       - jenkins
      state: latest

   - name: stop jenkins
     become: yes
     service: name=jenkins state=stopped

   - name: Setup Wizard disable
     lineinfile:
         path: /etc/default/jenkins
         line: 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false"'
         state: present






   - name: Creat user folder
     file:
        path: /var/lib/jenkins/users/
        state: directory
        owner: jenkins
        group: jenkins


   - name: copy directory users
     copy:
        src: xml_jenkins/users/
        dest: /var/lib/jenkins/users/

   - name: copy credential
     copy:
        src: xml_jenkins/credentials.xml
        dest: /var/lib/jenkins/credentials.xml

   - name: copy SSHBuildWrapper conf
     copy:
        src: xml_jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
        dest: /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml





   - name: copy Golang_config_jenkins
     copy:
        src: xml_jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
        dest: /var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml



   - name: Change directory permissions
     file:
        path: /var/lib/jenkins/users
        state: directory
        owner: jenkins
        group: jenkins
        mode: '700'

   - name: Change file permissions
     file:
        path: /var/lib/jenkins/users/users.xml
        owner: jenkins
        group: jenkins
        mode: '0644'


   - name: start Jenkins
     become: yes
     sysvinit:
       name: jenkins
       state: started

   - name: pause for start jenkins app
     shell: 'sleep 30'

   - name: Install plugin
     community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: admin
        url_password: admin
        url: http://localhost:8080
     with_items:
          - credentials
          - credentials-binding
          - Pipeline
          - golang
          - git
          - github
          - SSH
          - GitHub Branch Source
          - SSH Build Agents
          - nexus-artifact-uploader
          - build-trigger
     register: plugin_result
     until: plugin_result is success
     retries: 5
     delay: 10


   - include_tasks: create_job.yaml
