---
- name: Install Nexus
  hosts: localhost


  tasks:

   - name: add key java 8 for drbian 11
     apt_key:
       url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
   - apt_repository:
       repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bullseye main
       state: present
       update_cache: true

   - name: Install OpenJDK 8
     apt:
       name: adoptopenjdk-8-hotspot-jre
       state: present


   - name: download ansible-thoteam.nexus3-oss
     ansible.builtin.shell: ansible-galaxy install ansible-thoteam.nexus3-oss


   - name: start playbook2
     action: shell ansible-playbook for_nexus.yaml
