version: '3'

services:

  nexus:
    container_name: nexustest
    build: ./nexus/
    stdin_open: true
    networks:
        lan:
          ipv4_address: 172.20.0.4
    ports:
      - 81:8081

  jenkins:
    container_name: jenkinstest
    build: ./
    stdin_open: true
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8080
    networks:
        lan:
          ipv4_address: 172.20.0.5

networks:
    lan:
      ipam:
          config:
              - subnet: "172.20.0.0/24"
