---
- name: Install Nexus
  hosts: localhost
  become: yes

  vars:
    nexus_timezone: 'Europa/Minsk'
    nexus_admin_password: "admin"
    nexus_anonymous_access: false
    httpd_setup_enable: false
    nexus_delete_default_repos: true
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse

    nexus_roles:
      - id: uploader # maps to the LDAP group
        name: uploader
        description: All uploader
        privileges:
          - nx-repository-view-raw-world-cloud-build-add
          - nx-repository-view-raw-world-cloud-build-browse
          - nx-repository-view-raw-world-cloud-build-edit
#          - nx-repository-view-*-*-*
        roles: []
      - id: downloader # maps to the LDAP group
        name: downloader
        description: All downloader
        privileges:
          - nx-repository-view-*-*-*
        roles: []

    nexus_local_users:
      - username: uploader
        first_name: uploader
        last_name: uploader
        email: anttohha@upload
        password: "uploader"
        roles:
          - uploader
      - username: downloader
        first_name: downloader
        last_name: downloader
        email: anttohha@download
        password: "downloader"
        roles:
          - downloader
#    nexus_blobstores:
#      - name: company-artifacts
#        path: /var/nexus/blobs/company-artifacts

    # Change nexus_config_raw to true for create raw repository
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: world-cloud-build
      version_policy: release
      write_policy: allow  # one of "allow", "allow_once" or "deny"
      strict_content_validation: false


  roles:
     - ansible-thoteam.nexus3-oss
