- name: Create a jenkins task Jenkins
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/config3.xml') }}"
    name: "task-jenkins"
    password: admin
    url: http://localhost:8080
    user: admin
