---
- name: For stag and prod
  hosts: staging.vm, production.vm
  become: yes

  tasks:

   - name: Install jq packages
     become: yes
     apt:
      name: jq
      state: present

   - name: Creates directory /opt/wordcloud for service
     file:
      path: /opt/wordcloud
      state: directory


   - name: Copy service file
     copy:
      src: wordcloud.service
      dest:  /etc/systemd/system/wordcloud.service

   - name: Start wordcloud
     ansible.builtin.service:
      name: wordcloud
      state: started
