# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder "." , "/vagrant", disabled: false

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end


config.vm.define "jenkins.vm" do |jenkins|
   jenkins.vm.hostname = "jenkins.vm"
   jenkins.vm.network "private_network", ip: "192.168.56.10"
   jenkins.vm.provision "ansible_local" do |ansible|











    ansible.galaxy_role_file = 'requirements.yaml'
    ansible.playbook = "install.yaml"
    ansible.become = true

 end
end
end
