# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder "." , "/vagrant", disabled: false

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end


config.vm.define "jenkins.vm" do |jenkins|
   jenkins.vm.hostname = "jenkins.vm"
   jenkins.vm.network "private_network", ip: "192.168.56.10"
   jenkins.vm.provision "ansible_local" do |ansible|


     ansible.install_mode = "pip"




     ansible.pip_install_cmd = "sudo apt install -y python3-pip && sudo ln -s -f /usr/bin/pip3 /usr/bin/pip"
     ansible.compatibility_mode = "2.0"
     ansible.install_mode = "pip"
     #ansible.version = "2.12.4"
     ansible.playbook = "install.yaml"
      ansible.become = true


 end
end
end
