---
- name: Install apache2 and run
  become: yes
  hosts: localhost

  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
    - name: install php
      apt: name=php state=latest
    - name: Download html page
      action: shell sudo wget https://raw.githubusercontent.com/Fenikks/itacade$
    - name: Download php page
      action: shell sudo wget https://raw.githubusercontent.com/Fenikks/itacade$
    - name: copy html
      copy:
        src: index.html
        dest: /var/www/html
