---
- name: Install apache2 and run
  become: yes
  hosts: localhost

  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest
    - name: install php
      apt: name=php state=latest
    - name: Download html page
      action: shell sudo wget https://raw.githubusercontent.com/Fenikks/itacademy-devops-files/master/03-lxc/index.html
    - name: Download php page
      action: shell sudo wget https://raw.githubusercontent.com/Fenikks/itacademy-devops-files/master/03-lxc/index.php
    - name: copy html
      copy:
        src: index.html
        dest: /var/www/html
    - name: wget php.conf
      action: shell sudo wget https://raw.githubusercontent.com/anttohha/devops-hometasks/master/task-03/php.conf
    - name: copy html
      copy:
        src: php.conf
        dest: /etc/apache2/sites-available/
    - name: Download html page
      action: shell echo 'Listen 8081' >> /etc/apache2/ports.conf
      
      
      
      
      

