---
- name: install to slave1
  become: yes
  hosts: slave1

  tasks:
    - name: Install nano
      yum: name=nano state=latest

    - name: install puppet_agent
      yum: name=puppet-agent state=latest

-name: install to slave2
 become: yes
 hosts: slave2

 tasks:
     - name: install puppet_agent
       yum: name=puppet-agent state=latest



 -name: install to master
  become: yes
  hosts: master

  tasks:
     - name: install puppetserver
       yum: name=puppetserver state=latest
               
