---
- name: install to slave1
  become: yes
  hosts: slave1

  tasks:
    - name: Install nano
      yum: name=nano state=latest
    - name: add repositoriy to agent slave1
      action: rpm -Uvh https://yum.puppet.com/puppet6-release-el-8.noarch.rpm  

    - name: install puppet_agent
      yum: name=puppet-agent state=latest

-name: install to slave2
 become: yes
 hosts: slave2

 tasks:
     - name: add repositoriy to slave for agents slave2
       action: rpm -Uvh https://yum.puppet.com/puppet6-release-el-8.noarch.rpm

     - name: install puppet_agent
       yum: name=puppet-agent state=latest



 -name: install to master
  become: yes
  hosts: master

  tasks:
     - name: add repositoriy to master puppetserver
       action: shell  sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
     - name: add repositoriy to master 2
       action: shell sudo dnf -y install https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
     - name: install puppetserver
       yum: name=puppetserver state=latest
     - name: add to firewall
       action: firewall-cmd --permanent --add-port=8140/tcp
