- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/config2.xml') }}"
    name: "test-check"
    password: admin
    url: http://localhost:8080
    user: admin


- name: Create a jenkins build
  community.general.jenkins_build:
    name: "test-check"
    state: present
    user: admin
    password: admin
    url: http://localhost:8080
