- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/config.xml') }}"
    name: "go"
    url: http://localhost:8080

- name: Create a jenkins build
  community.general.jenkins_build:
    name: "go"
    build_number: 1
    state: present
    url: http://localhost:8080
